name: flutter_neumorphic
description: A new Flutter package.
version: 1.0.0
author: Florent Champigny <champigny.florent@gmail.com>
homepage: https://github.com/florent37/Flutter-Neumorphic

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter: