name: flutter_neumorphic
description: A complete, ready to use, Neumorphic ui kit for Flutter.
version: 1.0.0
authors: [
  Florent Champigny <champigny.florent@gmail.com>,
  Olivier Bonvila,
  Gyl Jean Lambert <almighty972@gmail.com>
]
homepage: https://github.com/Idean/Flutter-Neumorphic
issue_tracker: https://github.com/Idean/Flutter-Neumorphic/issues

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
